#!/usr/bin/env sh
# azd postprovision hook (POSIX / sh).
#
# Runs automatically after `azd provision`. It provisions the Foundry IQ
# knowledge base, creates local and hosted toolbox connections, and stores both
# endpoints — collapsing every manual provisioning step into a single
# `azd provision`.
#
# Wire it up by adding this to the azure.yaml generated by `azd ai agent init`:
#
#   hooks:
#     postprovision:
#       posix:
#         shell: sh
#         run: ./src/<agent-name>/hooks/postprovision.sh
#       windows:
#         shell: pwsh
#         run: ./src/<agent-name>/hooks/postprovision.ps1

set -e

# Run from the sample directory (the parent of hooks/) so provision_kb.py and
# the toolbox YAML files resolve no matter which directory azd invokes the hook.
cd "$(CDPATH= cd "$(dirname "$0")/.." && pwd)"

# AZURE_SEARCH_ENDPOINT is a prerequisite (your existing Azure AI Search service).
if [ -z "$AZURE_SEARCH_ENDPOINT" ]; then
  echo "AZURE_SEARCH_ENDPOINT is not set. Run: azd env set AZURE_SEARCH_ENDPOINT \"https://<your-search>.search.windows.net\"" >&2
  exit 1
fi

# Derive the Azure OpenAI endpoint from the Foundry project endpoint when unset.
if [ -z "$AZURE_OPENAI_ENDPOINT" ] && [ -n "$FOUNDRY_PROJECT_ENDPOINT" ]; then
  export AZURE_OPENAI_ENDPOINT="$(printf '%s' "$FOUNDRY_PROJECT_ENDPOINT" | sed -E 's#/api/projects/.*$##')"
fi

echo "Provisioning the Foundry IQ knowledge base..."
python -m pip install -q requests azure-identity python-dotenv
python provision_kb.py   # stores the KB MCP endpoint as KB_MCP_ENDPOINT

KB="$(azd env get-value KB_MCP_ENDPOINT)"
if [ -z "$KB" ]; then
  echo "provision_kb.py did not set KB_MCP_ENDPOINT." >&2
  exit 1
fi

echo "Creating the hosted knowledge-base-mcp connection..."
# --force upserts so the hook is safe to re-run on every azd provision.
azd ai connection create knowledge-base-mcp --kind remote-tool --force \
  --target "$KB" --auth-type agentic-identity \
  --audience https://search.azure.com --metadata "ApiType=Azure"

echo "Creating the local knowledge-base-mcp-local connection..."
azd ai connection create knowledge-base-mcp-local --kind remote-tool --force \
  --target "$KB" --auth-type user-entra-token \
  --audience https://search.azure.com --metadata "ApiType=Azure"

# Toolbox versions are immutable and 'create' has no upsert flag, so skip each
# toolbox if it already exists (for example, on a repeat azd provision).
TMPDIR_KB="$(mktemp -d)"
trap 'rm -rf "$TMPDIR_KB"' EXIT

ensure_toolbox() {
  NAME="$1"
  CONFIG="$2"
  echo "Creating the $NAME toolbox..."
  if azd ai toolbox show "$NAME" >/dev/null 2>&1; then
    echo "Toolbox $NAME already exists; skipping create."
  else
    # Resolve the KB endpoint into a temporary YAML file. The extension requires
    # the temporary file to retain a .yaml suffix.
    RESOLVED="$TMPDIR_KB/$NAME.yaml"
    KB="$KB" awk '{ gsub(/\$\{KB_MCP_ENDPOINT\}/, ENVIRON["KB"]); print }' "$CONFIG" > "$RESOLVED"
    azd ai toolbox create "$NAME" --from-file "$RESOLVED"
  fi
}

ensure_toolbox knowledge-base ./toolbox.yaml
ensure_toolbox knowledge-base-local ./toolbox.local.yaml

# The toolbox's unversioned MCP alias is deterministic from the project endpoint.
PROJ="$(azd env get-value FOUNDRY_PROJECT_ENDPOINT | sed 's#/*$##')"
DEPLOYMENT_TOOLBOX="$PROJ/toolboxes/knowledge-base/mcp?api-version=v1"
LOCAL_TOOLBOX="$PROJ/toolboxes/knowledge-base-local/mcp?api-version=v1"
azd env set TOOLBOX_DEPLOYMENT_ENDPOINT "$DEPLOYMENT_TOOLBOX"
azd env set TOOLBOX_ENDPOINT "$LOCAL_TOOLBOX"

echo "Done. TOOLBOX_ENDPOINT = $LOCAL_TOOLBOX"
echo "Done. TOOLBOX_DEPLOYMENT_ENDPOINT = $DEPLOYMENT_TOOLBOX"
