#!/usr/bin/env sh
# azd postprovision hook (POSIX / sh).
#
# Runs automatically after `azd provision`. It provisions the Foundry IQ
# knowledge base, creates local and deployed-agent toolboxes, and stores their
# endpoints — collapsing every manual provisioning step into one `azd provision`.
#
# Wire it up by adding this to the azure.yaml generated by `azd ai agent init`:
#
#   hooks:
#     postprovision:
#       posix:
#         shell: sh
#         run: ./src/<agent-name>/hooks/postprovision.sh
#       windows:
#         shell: pwsh
#         run: ./src/<agent-name>/hooks/postprovision.ps1

set -e

# Run from the sample directory (the parent of hooks/) so provision_kb.py and
# toolbox.yaml resolve no matter which directory azd invokes the hook from.
cd "$(CDPATH= cd "$(dirname "$0")/.." && pwd)"

# AZURE_SEARCH_ENDPOINT is a prerequisite (your existing Azure AI Search service).
if [ -z "$AZURE_SEARCH_ENDPOINT" ]; then
  echo "AZURE_SEARCH_ENDPOINT is not set. Run: azd env set AZURE_SEARCH_ENDPOINT \"https://<your-search>.search.windows.net\"" >&2
  exit 1
fi

# Derive the Azure OpenAI endpoint from the Foundry project endpoint when unset.
if [ -z "$AZURE_OPENAI_ENDPOINT" ] && [ -n "$FOUNDRY_PROJECT_ENDPOINT" ]; then
  export AZURE_OPENAI_ENDPOINT="$(printf '%s' "$FOUNDRY_PROJECT_ENDPOINT" | sed -E 's#/api/projects/.*$##')"
fi

echo "Provisioning the Foundry IQ knowledge base..."
python -m pip install -q requests azure-identity python-dotenv
python provision_kb.py   # stores the KB MCP endpoint as KB_MCP_ENDPOINT

KB="$(azd env get-value KB_MCP_ENDPOINT)"
if [ -z "$KB" ]; then
  echo "provision_kb.py did not set KB_MCP_ENDPOINT." >&2
  exit 1
fi

echo "Creating the knowledge base connections..."
# --force upserts so the hook is safe to re-run on every azd provision.
azd ai connection create knowledge-base-mcp --kind remote-tool --force \
  --target "$KB" --auth-type agentic-identity \
  --audience https://search.azure.com --metadata "ApiType=Azure"
azd ai connection create knowledge-base-mcp-local --kind remote-tool --force \
  --target "$KB" --auth-type user-entra-token \
  --audience https://search.azure.com --metadata "ApiType=Azure"

create_toolbox() {
  NAME="$1"
  TEMPLATE="$2"
  if azd ai toolbox show "$NAME" >/dev/null 2>&1; then
    echo "Toolbox $NAME already exists; skipping create."
    return
  fi

  # toolbox.yaml references ${KB_MCP_ENDPOINT} for the tool's server_url; resolve
  # it into a temp file so the toolbox points at this deployment's KB endpoint.
  # The temp file must keep a .yaml extension — azd ai toolbox create rejects others.
  TMPDIR_KB="$(mktemp -d)"
  trap 'rm -rf "$TMPDIR_KB"' 0
  TMP="$TMPDIR_KB/toolbox.yaml"
  KB="$KB" awk '{ gsub(/\$\{KB_MCP_ENDPOINT\}/, ENVIRON["KB"]); print }' "$TEMPLATE" > "$TMP"
  azd ai toolbox create "$NAME" --from-file "$TMP"
  rm -rf "$TMPDIR_KB"
  trap - 0
}

echo "Creating the knowledge base toolboxes..."
create_toolbox knowledge-base ./toolbox.yaml
create_toolbox knowledge-base-local ./toolbox-local.yaml

# Use user identity locally and agentic identity in the deployed agent.
PROJ="$(azd env get-value FOUNDRY_PROJECT_ENDPOINT | sed 's#/*$##')"
LOCAL_TOOLBOX="$PROJ/toolboxes/knowledge-base-local/mcp?api-version=v1"
AGENT_TOOLBOX="$PROJ/toolboxes/knowledge-base/mcp?api-version=v1"
azd env set TOOLBOX_ENDPOINT "$LOCAL_TOOLBOX"
azd env set TOOLBOX_AGENT_ENDPOINT "$AGENT_TOOLBOX"

echo "Done. TOOLBOX_ENDPOINT = $LOCAL_TOOLBOX"
echo "Done. TOOLBOX_AGENT_ENDPOINT = $AGENT_TOOLBOX"
