#!/usr/bin/env pwsh
# azd postprovision hook (Windows / pwsh).
#
# Runs automatically after `azd provision`. It provisions the Foundry IQ
# knowledge base, creates local and deployed-agent toolboxes, and stores their
# endpoints — collapsing every manual provisioning step into one `azd provision`.
#
# Wire it up by adding this to the azure.yaml generated by `azd ai agent init`:
#
#   hooks:
#     postprovision:
#       posix:
#         shell: sh
#         run: ./src/<agent-name>/hooks/postprovision.sh
#       windows:
#         shell: pwsh
#         run: ./src/<agent-name>/hooks/postprovision.ps1

$ErrorActionPreference = "Stop"

# PowerShell does not stop on a non-zero exit code from a native command (like
# azd), so check $LASTEXITCODE after each azd call and fail loudly.
function Invoke-Checked {
    param([scriptblock] $Script, [string] $What)
    & $Script
    if ($LASTEXITCODE -ne 0) { throw "$What failed (exit $LASTEXITCODE)." }
}

# Run from the sample directory (the parent of hooks/) so provision_kb.py and
# toolbox.yaml resolve no matter which directory azd invokes the hook from.
Set-Location (Split-Path -Parent $PSScriptRoot)

# AZURE_SEARCH_ENDPOINT is a prerequisite (your existing Azure AI Search service).
if (-not $env:AZURE_SEARCH_ENDPOINT) {
    throw "AZURE_SEARCH_ENDPOINT is not set. Run: azd env set AZURE_SEARCH_ENDPOINT ""https://<your-search>.search.windows.net"""
}

# Derive the Azure OpenAI endpoint from the Foundry project endpoint when unset.
if (-not $env:AZURE_OPENAI_ENDPOINT -and $env:FOUNDRY_PROJECT_ENDPOINT) {
    $env:AZURE_OPENAI_ENDPOINT = ($env:FOUNDRY_PROJECT_ENDPOINT -replace '/api/projects/.*$', '')
}

Write-Host "Provisioning the Foundry IQ knowledge base..."
Invoke-Checked { python -m pip install -q requests azure-identity python-dotenv } "pip install"
Invoke-Checked { python provision_kb.py } "provision_kb.py"   # stores the KB MCP endpoint as KB_MCP_ENDPOINT

$kb = azd env get-value KB_MCP_ENDPOINT
if (-not $kb) { throw "provision_kb.py did not set KB_MCP_ENDPOINT." }

Write-Host "Creating the knowledge base connections..."
# --force upserts so the hook is safe to re-run on every azd provision.
Invoke-Checked {
    azd ai connection create knowledge-base-mcp --kind remote-tool --force `
        --target $kb --auth-type agentic-identity `
        --audience https://search.azure.com --metadata "ApiType=Azure"
} "connection create"
Invoke-Checked {
    azd ai connection create knowledge-base-mcp-local --kind remote-tool --force `
        --target $kb --auth-type user-entra-token `
        --audience https://search.azure.com --metadata "ApiType=Azure"
} "local connection create"

function New-ToolboxIfMissing {
    param([string] $Name, [string] $Template)

    $prevEap = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    azd ai toolbox show $Name *> $null
    $toolboxExists = ($LASTEXITCODE -eq 0)
    $ErrorActionPreference = $prevEap
    if ($toolboxExists) {
        Write-Host "Toolbox $Name already exists; skipping create."
        return
    }

    # toolbox.yaml references ${KB_MCP_ENDPOINT} for the tool's server_url; resolve
    # it into a temp file so the toolbox points at this deployment's KB endpoint.
    # The temp file must keep a .yaml extension — azd ai toolbox create rejects others.
    $resolved = (Get-Content $Template -Raw).Replace('${KB_MCP_ENDPOINT}', $kb)
    $tmp = Join-Path ([System.IO.Path]::GetTempPath()) "toolbox-$([System.Guid]::NewGuid()).yaml"
    Set-Content -Path $tmp -Value $resolved -NoNewline
    try {
        Invoke-Checked { azd ai toolbox create $Name --from-file $tmp } "toolbox create"
    }
    finally {
        Remove-Item $tmp -ErrorAction SilentlyContinue
    }
}

Write-Host "Creating the knowledge base toolboxes..."
New-ToolboxIfMissing "knowledge-base" "./toolbox.yaml"
New-ToolboxIfMissing "knowledge-base-local" "./toolbox-local.yaml"

# Use user identity locally and agentic identity in the deployed agent.
$proj = (azd env get-value FOUNDRY_PROJECT_ENDPOINT).TrimEnd('/')
$localToolbox = "$proj/toolboxes/knowledge-base-local/mcp?api-version=v1"
$agentToolbox = "$proj/toolboxes/knowledge-base/mcp?api-version=v1"
Invoke-Checked { azd env set TOOLBOX_ENDPOINT $localToolbox } "env set TOOLBOX_ENDPOINT"
Invoke-Checked { azd env set TOOLBOX_AGENT_ENDPOINT $agentToolbox } "env set TOOLBOX_AGENT_ENDPOINT"

Write-Host "Done. TOOLBOX_ENDPOINT = $localToolbox"
Write-Host "Done. TOOLBOX_AGENT_ENDPOINT = $agentToolbox"
